numpy


In [3]:
import numpy as np
np.__version__

'2.1.3'

In [2]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

converting list to array


In [3]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

arange()

In [4]:
 np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
np.arange(3.0)

array([0., 1., 2.])

In [6]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
ar=np.arange(-10,10)
ar

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [8]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

zeros()

In [10]:
np.zeros(5,int)


array([0, 0, 0, 0, 0])

In [16]:
zr=np.zeros((2,10),int)
print(zr)
type(zr)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


numpy.ndarray

In [14]:
np.zeros((8,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

ones()

In [22]:
on=ones(2)
print(on)

[1. 1.]


In [23]:
ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
rand(3,2)
random.rand(5) 

NameError: name 'rand' is not defined

In [28]:
np.random.rand(5)

array([0.63657989, 0.23096409, 0.23523941, 0.71678777, 0.37406139])

In [34]:
np.random.rand(3,5)

array([[0.87827307, 0.81457407, 0.19933667, 0.58641131, 0.83167471],
       [0.16254928, 0.03511103, 0.86853969, 0.20616712, 0.43548556],
       [0.7799418 , 0.30436281, 0.23986636, 0.09379922, 0.3788668 ]])

In [38]:
np.random.randint(2,6,2)

array([4, 2], dtype=int32)

In [3]:
np.random.randint(5,9)

7

In [4]:
np.random.randint(10,40,(10,10))   #generates the element b/w 10 to 40 10*10 matrix

array([[32, 29, 24, 38, 28, 15, 22, 16, 32, 11],
       [10, 37, 33, 23, 37, 16, 11, 31, 20, 24],
       [27, 38, 38, 18, 12, 37, 10, 37, 11, 17],
       [23, 20, 16, 38, 14, 25, 39, 24, 19, 33],
       [19, 12, 20, 34, 23, 22, 24, 14, 30, 26],
       [26, 23, 26, 16, 32, 37, 33, 13, 24, 31],
       [19, 20, 27, 24, 22, 18, 34, 13, 31, 26],
       [38, 24, 22, 10, 19, 29, 32, 26, 18, 10],
       [32, 13, 20, 14, 27, 26, 35, 14, 31, 29],
       [28, 36, 28, 38, 30, 32, 29, 22, 37, 26]], dtype=int32)

reshape()


In [5]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
np.arange(1,13).reshape(6,2)      #the reshape should match the no of elements

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [16]:
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

 slicing in matrix()

In [16]:
b=np.random.randint(10,20,(5,4))
b

array([[16, 19, 18, 18],
       [10, 15, 13, 17],
       [10, 15, 16, 16],
       [16, 15, 10, 13],
       [16, 19, 10, 12]], dtype=int32)

In [17]:
b[:]

array([[16, 19, 18, 18],
       [10, 15, 13, 17],
       [10, 15, 16, 16],
       [16, 15, 10, 13],
       [16, 19, 10, 12]], dtype=int32)

In [21]:
b[1:2]          #display few elements

array([[10, 15, 13, 17]], dtype=int32)

In [22]:
b[1,2]          #displays a specfic value

np.int32(13)

In [23]:
b[1,-1]

np.int32(17)

operations


In [28]:
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [30]:
arr2=np.random.randint(0,100,(10,10))
arr2

array([[84, 99, 64, 96, 41, 40, 83, 38,  1, 30],
       [38, 68, 65, 85, 66, 75, 43, 23, 44, 40],
       [20, 25, 82, 40, 44, 63, 89, 61, 95, 66],
       [ 8,  4, 42, 26, 45, 38,  9, 71, 70, 70],
       [ 1, 25, 95, 89, 68,  0, 48, 46, 85, 46],
       [96, 60, 90, 99, 22, 96, 45, 88,  2, 87],
       [88, 69,  7, 45, 17, 78, 14, 79, 10, 55],
       [82, 97, 80, 77, 13, 59, 69, 12, 15, 93],
       [11, 45, 26, 72, 59, 55, 15, 82, 28, 34],
       [81, 11, 39, 84, 86, 84, 16, 70, 35, 37]], dtype=int32)

In [31]:
arr2[:]

array([[84, 99, 64, 96, 41, 40, 83, 38,  1, 30],
       [38, 68, 65, 85, 66, 75, 43, 23, 44, 40],
       [20, 25, 82, 40, 44, 63, 89, 61, 95, 66],
       [ 8,  4, 42, 26, 45, 38,  9, 71, 70, 70],
       [ 1, 25, 95, 89, 68,  0, 48, 46, 85, 46],
       [96, 60, 90, 99, 22, 96, 45, 88,  2, 87],
       [88, 69,  7, 45, 17, 78, 14, 79, 10, 55],
       [82, 97, 80, 77, 13, 59, 69, 12, 15, 93],
       [11, 45, 26, 72, 59, 55, 15, 82, 28, 34],
       [81, 11, 39, 84, 86, 84, 16, 70, 35, 37]], dtype=int32)

In [32]:
 arr2[::-1]           #prints the rows in reverse

array([[81, 11, 39, 84, 86, 84, 16, 70, 35, 37],
       [11, 45, 26, 72, 59, 55, 15, 82, 28, 34],
       [82, 97, 80, 77, 13, 59, 69, 12, 15, 93],
       [88, 69,  7, 45, 17, 78, 14, 79, 10, 55],
       [96, 60, 90, 99, 22, 96, 45, 88,  2, 87],
       [ 1, 25, 95, 89, 68,  0, 48, 46, 85, 46],
       [ 8,  4, 42, 26, 45, 38,  9, 71, 70, 70],
       [20, 25, 82, 40, 44, 63, 89, 61, 95, 66],
       [38, 68, 65, 85, 66, 75, 43, 23, 44, 40],
       [84, 99, 64, 96, 41, 40, 83, 38,  1, 30]], dtype=int32)

In [35]:
arr2

array([[84, 99, 64, 96, 41, 40, 83, 38,  1, 30],
       [38, 68, 65, 85, 66, 75, 43, 23, 44, 40],
       [20, 25, 82, 40, 44, 63, 89, 61, 95, 66],
       [ 8,  4, 42, 26, 45, 38,  9, 71, 70, 70],
       [ 1, 25, 95, 89, 68,  0, 48, 46, 85, 46],
       [96, 60, 90, 99, 22, 96, 45, 88,  2, 87],
       [88, 69,  7, 45, 17, 78, 14, 79, 10, 55],
       [82, 97, 80, 77, 13, 59, 69, 12, 15, 93],
       [11, 45, 26, 72, 59, 55, 15, 82, 28, 34],
       [81, 11, 39, 84, 86, 84, 16, 70, 35, 37]], dtype=int32)

In [36]:
arr2[::-2]

array([[81, 11, 39, 84, 86, 84, 16, 70, 35, 37],
       [82, 97, 80, 77, 13, 59, 69, 12, 15, 93],
       [96, 60, 90, 99, 22, 96, 45, 88,  2, 87],
       [ 8,  4, 42, 26, 45, 38,  9, 71, 70, 70],
       [38, 68, 65, 85, 66, 75, 43, 23, 44, 40]], dtype=int32)

In [37]:
arr2[::-3]

array([[81, 11, 39, 84, 86, 84, 16, 70, 35, 37],
       [88, 69,  7, 45, 17, 78, 14, 79, 10, 55],
       [ 8,  4, 42, 26, 45, 38,  9, 71, 70, 70],
       [84, 99, 64, 96, 41, 40, 83, 38,  1, 30]], dtype=int32)

In [38]:
arr.max()

np.int64(5)

In [39]:
arr.min()

np.int64(0)

In [40]:
arr.mean()

np.float64(2.5)

In [17]:
mat = np.arange(0,100).reshape(10,10)

In [18]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [19]:
row=4
col=5

In [20]:
row

4

In [21]:
col

5

In [22]:
mat[row,col]

np.int64(45)

In [23]:
mat[6]    #by default it prints the rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [24]:
mat[:,col]   

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [25]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])